Using Arrays and scalars      
9/29

In [2]:
pwd

u'/Users/Sean'

In [3]:
import numpy as np

In [4]:
5/2

2

In [5]:
5./2

2.5

In [10]:
#for python 2
from __future__ import division
#then we do not need to worry about float or integer

In [11]:
5/2

2.5

In [ ]:
#######################

In [12]:
#multi-dimention array
arr1 = np.array([[1,2,3,4],[11,22,33,44]])

In [13]:
arr1

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
#multiply numbers at same spot 
arr1 * arr1

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936]])

In [15]:
arr1 - arr1 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.09090909,  0.04545455,  0.03030303,  0.02272727]])

In [18]:
arr1 ** 3 

array([[    1,     8,    27,    64],
       [ 1331, 10648, 35937, 85184]])